# config/stream_processor.yaml
---
stream_processor:
  group_by: ["ip.src", "ip.dst", "ipv6.src", "ipv6.dst", "tcp.srcport", "tcp.dstport", "udp.srcport", "udp.dstport"]
  aggregate:
    fields: [
      "frame.len", "tcp.len", "udp.length", 
      "tcp.flags.syn", "tcp.flags.ack", "tcp.flags.fin", "tcp.flags.reset", 
      "tcp.flags.push", "tcp.flags.urg", "tcp.flags.cwr", "tcp.flags.ece"
    ]
    function: "sum"
